// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Projekt.Server.Helpers;

#nullable disable

namespace Projekt.Server.Migrations
{
    [DbContext(typeof(StudyContext))]
    [Migration("20241015205851_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Projekt.Shared.Entities.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SentQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SentQuestionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ContentPoints")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItemId");

                    b.HasIndex("CourseId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("ItemId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Projekt.Shared.Entities.SentItem", b =>
                {
                    b.Property<int>("SentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SentItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("SentItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("SentItem");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.SentQuestion", b =>
                {
                    b.Property<int>("SentQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SentQuestionId"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SentItemId")
                        .HasColumnType("integer");

                    b.HasKey("SentQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SentItemId");

                    b.ToTable("SentQuestion");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2024, 10, 15, 20, 58, 51, 133, DateTimeKind.Utc).AddTicks(3711),
                            Login = "admin",
                            Password = "$2a$11$/5SRollwPNZoOqblOUm6WemMNeVTa1y.nOnlO2B0.p/HIXKBywglC",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2024, 10, 15, 20, 58, 51, 249, DateTimeKind.Utc).AddTicks(5169),
                            Login = "student",
                            Password = "$2a$11$Iyd1yyma7OauXgTnXZ1.re0.JFMgj8BrTqbeVY9MLLHZ.F8R8zEf6"
                        });
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Answer", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");

                    b.HasOne("Projekt.Shared.Entities.SentQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("SentQuestionId");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Course", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Item", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Course", "Course")
                        .WithMany("Items")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Question", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Item", "Item")
                        .WithMany("Questions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.SentItem", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Item", "Item")
                        .WithMany("FilledItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Shared.Entities.User", "User")
                        .WithMany("FilledItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.SentQuestion", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Question", "Question")
                        .WithMany("SentQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt.Shared.Entities.SentItem", "SentItem")
                        .WithMany("SentQuestions")
                        .HasForeignKey("SentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SentItem");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.User", b =>
                {
                    b.HasOne("Projekt.Shared.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Course", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Item", b =>
                {
                    b.Navigation("FilledItems");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("SentQuestions");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.SentItem", b =>
                {
                    b.Navigation("SentQuestions");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.SentQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Projekt.Shared.Entities.User", b =>
                {
                    b.Navigation("FilledItems");
                });
#pragma warning restore 612, 618
        }
    }
}
